ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      width = 3,
      numericInput(inputId = "sample_size",
                   label = "Sample Size",
                   value = 10000,
                   min = 10,
                   max = 100000),
      h3("Effects of U"),
      column(6, numericInput(inputId = "U_on_X",
                             label = "U on X",
                             value = 0.1)),
      column(6, numericInput(inputId = "U_on_Y",
                             label = "U on Y",
                             value = 0.1)),
      h3("Effect of X"),
      numericInput(inputId = "X_on_Y",
                   label = "Effect of X on Y",
                   value = 0.1),
      h3("Independent Instrumental Variables"),
      sliderInput(inputId = "n_indIVs", label = "Number of independent IVs to include",
                  value = 1, min = 0, max = 10, step = 1),
      radioButtons(inputId = "n_cats",
                   label = "Number of categories of Z",
                   choices = c("2", "3")),
      uiOutput(outputId = "IVs_ps"),
      h4("Effect of independent IVs on X"),
      uiOutput(outputId = "indIVs_on_X"),
      h4("Effect of independent IVs on Y"),
      uiOutput(outputId = "indIVs_on_Y"),
      h3("Correlated Instrumental Variables"),
      checkboxInput(inputId = "include_dep_IVs",
                    label = "Include a pair of dependent variables",
                    value = FALSE),
      conditionalPanel("input.include_dep_IVs",
                       sliderInput(inputId = "rho",
                                   label = "Correlation between dependend IVs",
                                   min = 0, max = 1, value = 0.5, step = 0.1),
                       numericInput(inputId = "depIV1_on_X",
                                    label = "Effect of dependent IV 1 on X",
                                    value = 0.1),
                       numericInput(inputId = "depIV2_on_X",
                                    label = "Effect of dependent IV 2 on X",
                                    value = 0.1)),
      actionButton(inputId = "simulate_data", label = "Simulate data")
    ),
    mainPanel(
      conditionalPanel("input.simulate_data > 0",
                       plotOutput("DAG_plotted")),
      conditionalPanel("input.simulate_data > 0",
                       plotOutput("plot_results")),
      conditionalPanel("input.simulate_data > 0",
                       DT::dataTableOutput("tidy_results")),
      conditionalPanel("input.simulate_data > 0",
                       DT::dataTableOutput("simulated_data")),
      width = 9
    )
  )
)